### ISSUE TITLE
cannot import _APY_LOADED

### ISSUE THREAD

**Issue by webbjj** [jobovy/streamtools#6]
After updating galpy. when importing streamtools I get the following error:

ImportError: cannot import name '_APY_LOADED' from 'galpy.df.df' (/usr/local/lib/python3.9/site-packages/galpy-1.8.0.dev0-py3.9-macosx-10.15-x86_64.egg/galpy/df/df.py)

I "think" this is because _APY_LOADED has moved to util.conversion? It seems to work when I make the change locally but I wasn't confident this was the actual fix.

**Comment by jobovy** [comment]
Is this using the latest version on GitHub? I think this was fixed in 4ab55cf4cbb1c2c27010b0b41b45cf2099c1a887.

**Comment by webbjj** [comment]
Ah I was pulling from a forked version, not the master.  My bad.
